- name: Add ethereum repositories
  apt_repository: repo={{ item }} update_cache=yes
  become: yes
  with_items:
  - ppa:ethereum/ethereum

- name: Create Installs directory
  file: path=~/Installs state=directory

- name: Symlink ~/Installs
  file: src=~/Installs dest=/tmp/Installs state=link

- name: Download Ethereum wallet
  get_url: url=https://github.com/ethereum/mist/releases/download/v0.9.3/Ethereum-Wallet-linux64-0-9-3.deb dest=~/Installs/Ethereum-Wallet-linux64-0-9-3.deb checksum=sha256:946b4b7dec1b6f2b58b6ef21d06a12dcee691fa2186baad7d99872f94240ced8
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Ethereum wallet
  apt: deb=/tmp/Installs/Ethereum-Wallet-linux64-0-9-3.deb
  become: yes

- name: Download Factom
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}
  with_items:
  - {url: "https://github.com/FactomProject/distribution/releases/download/v0.4.2.2/factom-amd64.deb", name: factom-amd64.deb, sha: "sha256:e7cb8c24bec50362e118ebc14f530a705a62a582c60ecfd8be3ba85f8cc8003e"}
  - {url: "https://github.com/FactomProject/distribution/releases/download/v0.4.2.1/enterprise-wallet-setup-amd64.deb", name: enterprise-wallet-setup-amd64.deb, sha: "sha256:31d563deae91513e9fdede8a7a57754f0c112de0a4ec3947de99f5793d6ec33c"}
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Factom
  apt: deb=/tmp/Installs/{{ item }}
  become: yes
  with_items:
  - factom-amd64.deb
  - enterprise-wallet-setup-amd64.deb

- name: Download VeriCoin installer
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}  mode=a+x
  with_items:
    - {url: "http://www.vericoin.info/downloads/VeriCoin_1.7_64bit.run", name: VeriCoin_1.7_64bit.run, sha: "sha256:5a3e0a8382071d5e7270f120c98892aab92656823df5aa38bff6de51f3f2e565"}
    - {url: "http://www.vericoin.info/downloads/Verium_1.1_64bit.run", name: Verium_1.1_64bit.run, sha: "sha256:fb7fe25384c0a4b99c6cb38ba2290719065f4beab4b8bac105111513d037766d"}

  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install ethereum CLI tools
  apt: pkg={{ item }}
  become: yes
  with_items:
  - ethereum

- name: Install unzip
  apt: pkg=unzip
  become: yes

- name: Download Waves wallet
  get_url: url=https://wavesplatform.com/files/WavesClient-1.0.0-beta.X-linux.deb dest=~/Installs/WavesClient-1.0.0-beta.X-linux.deb checksum="sha256:35859381d98521304eb9280316667d440ac0e179a8f31b3c177e8658f41a213d"
  register: waves_get_url_result
  until: waves_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Waves client
  apt: deb=/tmp/Installs/WavesClient-1.0.0-beta.X-linux.deb
  become: yes

- name: Download Wagerr wallet
  get_url: url=https://github.com/wagerr/wagerr/releases/download/v1.4.34.2/wagerr-1.4.34.2-x86_64-linux-gnu.tar.gz dest=~/Installs/wagerr-1.4.34.2-x86_64-linux-gnu.tar.gz
  register: wagerr_get_url_result
  until: wagerr_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Extract Wagerr wallet
  unarchive: src=~/Installs/wagerr-1.4.34.2-x86_64-linux-gnu.tar.gz remote_src=yes dest=~/Installs

- name: Download CryptoInsight
  get_url: url=https://github.com/cryptoinsightio/cryptoinsight-client/releases/download/1.0.2/CryptoInsight-1-0-2.AppImage dest=~/Installs/CryptoInsight-1-0-2.AppImage mode=u+rwx checksum=sha256:38ade55d6631ede28448aa66023eb3cb4553442057ad78632e6d28a078d8b3ff
  register: cryptoinsight_get_url_result
  until: cryptoinsight_get_url_result | succeeded
  retries: 3
  delay: 1
