- name: Create Installs directory
  file: path=~/Installs state=directory

- name: Symlink ~/Installs
  file: src=~/Installs dest=/tmp/Installs state=link

- name: Download Ethereum wallet
  get_url: url=https://github.com/ethereum/mist/releases/download/v0.11.1/Ethereum-Wallet-linux64-0-11-1.deb dest=~/Installs/Ethereum-Wallet-linux64-0-11-1.deb checksum=sha256:1abca9b43983e63df3514307fa4317baa7e9604e64136263fd44544d03a12c6d
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Ethereum wallet
  apt: deb=/tmp/Installs/Ethereum-Wallet-linux64-0-11-1.deb
  become: yes

- name: Download Factom
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}
  with_items:
  - {url: "https://github.com/FactomProject/distribution/releases/download/v6.1.0/factom-amd64.deb", name: factom-amd64.deb, sha: "sha256:6688accf975375aa81863d5bca144b66d72e78ba2896044ff3e901e83b0b6246"}
  - {url: "https://github.com/FactomProject/enterprise-wallet/archive/v0.2.0.0.zip", name: enterprise-wallet-v0.2.0.0.zip, sha: "sha256:2637bfef6dc98a49bcedbc4f771279e997a81944c0f8663b4243862e7daa45e1"}
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Factom
  apt: deb=/tmp/Installs/{{ item }}
  become: yes
  with_items:
  - factom-amd64.deb

- name: Download VeriCoin installer
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}  mode=a+x
  with_items:
    - {url: "https://cdn.vericonomy.com/vericoin/VeriCoin_1.7.2_64bit.run", name: VeriCoin_1.7.2_64bit.run, sha: "sha256:27c7a55216b54353035418362ebcb2d8a73d6683163fa4dfe7e1359969862a77"}
    - {url: "https://cdn.vericonomy.com/verium/Verium_1.2_64bit.run", name: Verium_1.2_64bit.run, sha: "sha256:d5766fecd86c3a04d718caf74efe548fb47d47a33c0c6e771ff58410abac6ca4"}
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install VeriCoin/Verium dependencies
  apt: pkg={{ item }}
  become: yes
  with_items:
    - git
    - build-essential
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libcurl4-openssl-dev
    - libboost-thread-dev
    - libssl-dev
    - libdb++-dev
    - libboost-program-options-dev
    - libminiupnpc-dev
    - libboost-all-dev
    - libqrencode-dev
    - libcurl4-gnutls-dev
    - libminizip-dev

- name: Install unzip
  apt: pkg=unzip
  become: yes

- name: Download Waves wallet
  get_url: url=https://wavesplatform.com/files/WavesDEX-linux.deb dest=~/Installs/WavesDEX-linux.deb checksum="sha256:c7e7c534de98b777942112561c23e4f175203167d7eb486c96ad83821df38991"
  register: waves_get_url_result
  until: waves_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Waves client
  apt: deb=/tmp/Installs/WavesDEX-linux.deb
  become: yes

- name: Download Wagerr wallet
  get_url: url=https://github.com/wagerr/wagerr/releases/download/v2.0.2/wagerr-2.0.2-x86_64-linux-gnu.tar.gz dest=~/Installs/wagerr-2.0.2-x86_64-linux-gnu.tar.gz checksum="sha256:883b1873d8624b08535cc3f4377446d9f5ad57c12a4177aa94095c1d440262c7"
  register: wagerr_get_url_result
  until: wagerr_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Extract Wagerr wallet
  unarchive: src=~/Installs/wagerr-2.0.2-x86_64-linux-gnu.tar.gz remote_src=yes dest=~/Installs

- name: Download Tezos wallet
  get_url: url=https://cryptonomic-wallet.nyc3.digitaloceanspaces.com/release_0.8.2b/Galleon-0.8.2-b.deb dest=~/Installs/Galleon_0.8.2-b_mainnet.deb checksum=sha256:7519b6ca3bbc6f28f87326e67011079d8f7365e3f4d28032c172e2db0599983e
  register: tezos_get_url_result
  until: tezos_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Tezos wallet
  apt: deb=/tmp/Installs/Galleon_0.8.2-b_mainnet.deb
  become: yes
