- name: Add ethereum repositories
  apt_repository: repo={{ item }} update_cache=yes
  become: yes
  with_items:
  - ppa:ethereum/ethereum

- name: Create Installs directory
  file: path=~/Installs state=directory

- name: Symlink ~/Installs
  file: src=~/Installs dest=/tmp/Installs state=link

- name: Download Ethereum wallet
  get_url: url=https://github.com/ethereum/mist/releases/download/v0.11.1/Ethereum-Wallet-linux64-0-11-1.deb dest=~/Installs/Ethereum-Wallet-linux64-0-11-1.deb checksum=sha256:1abca9b43983e63df3514307fa4317baa7e9604e64136263fd44544d03a12c6d
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Ethereum wallet
  apt: deb=/tmp/Installs/Ethereum-Wallet-linux64-0-11-1.deb
  become: yes

- name: Download Factom
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}
  with_items:
  - {url: "https://github.com/FactomProject/distribution/releases/download/v5.4.3/factom-amd64.deb", name: factom-amd64.deb, sha: "sha256:4c82f004f498cb710fd58b8a3bbcef45694e6bdb0d1b91157f0318f7f79649a2"}
  - {url: "https://github.com/FactomProject/enterprise-wallet/archive/v0.2.0.0.zip", name: enterprise-wallet-v0.2.0.0.zip, sha: "sha256:2637bfef6dc98a49bcedbc4f771279e997a81944c0f8663b4243862e7daa45e1"}
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Factom
  apt: deb=/tmp/Installs/{{ item }}
  become: yes
  with_items:
  - factom-amd64.deb

- name: Download VeriCoin installer
  get_url: url={{ item.url }} dest=~/Installs/{{ item.name }} checksum={{ item.sha }}  mode=a+x
  with_items:
    - {url: "https://cdn.vericonomy.com/vericoin/VeriCoin_1.7.2_64bit.run", name: VeriCoin_1.7.2_64bit.run, sha: "sha256:27c7a55216b54353035418362ebcb2d8a73d6683163fa4dfe7e1359969862a77"}
    - {url: "https://cdn.vericonomy.com/verium/Verium_1.2_64bit.run", name: Verium_1.2_64bit.run, sha: "sha256:d5766fecd86c3a04d718caf74efe548fb47d47a33c0c6e771ff58410abac6ca4"}
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install VeriCoin/Verium dependencies
  apt: pkg={{ item }}
  become: yes
  with_items:
    - build-essential
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libcurl4-openssl-dev
    - libboost-thread-dev
    - libssl-dev
    - libdb++-dev
    - libboost-program-options-dev
    - libminiupnpc-dev
    - libboost-all-dev
    - libqrencode-dev
    - freeglut3-dev
    - git
    - libminizip-dev

- name: Install ethereum CLI tools
  apt: pkg={{ item }} update_cache=yes
  become: yes
  with_items:
  - ethereum

- name: Install unzip
  apt: pkg=unzip
  become: yes

- name: Download Waves wallet
  get_url: url=https://wavesplatform.com/files/WavesClient-1.0.8-linux.deb dest=~/Installs/WavesClient-1.0.8-linux.deb checksum="sha256:2388b4106c1163371d5270b41f73a25331319c3575e1ee197292bf5f8de2cbba"
  register: waves_get_url_result
  until: waves_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Install Waves client
  apt: deb=/tmp/Installs/WavesClient-1.0.8-linux.deb
  become: yes

- name: Download Wagerr wallet
  get_url: url=https://github.com/wagerr/wagerr/releases/download/v2.0.2/wagerr-2.0.2-x86_64-linux-gnu.tar.gz dest=~/Installs/wagerr-2.0.2-x86_64-linux-gnu.tar.gz checksum="sha256:883b1873d8624b08535cc3f4377446d9f5ad57c12a4177aa94095c1d440262c7"
  register: wagerr_get_url_result
  until: wagerr_get_url_result | succeeded
  retries: 3
  delay: 1

- name: Extract Wagerr wallet
  unarchive: src=~/Installs/wagerr-2.0.2-x86_64-linux-gnu.tar.gz remote_src=yes dest=~/Installs

- name: Download CryptoInsight
  get_url: url=https://github.com/cryptoinsightio/cryptoinsight-client/releases/download/1.0.2/CryptoInsight-1-0-2.AppImage dest=~/Installs/CryptoInsight-1-0-2.AppImage mode=u+rwx checksum=sha256:38ade55d6631ede28448aa66023eb3cb4553442057ad78632e6d28a078d8b3ff
  register: cryptoinsight_get_url_result
  until: cryptoinsight_get_url_result | succeeded
  retries: 3
  delay: 1
